# Generated by Django 4.2.7 on 2023-11-20 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_form', models.CharField(max_length=70, verbose_name='Название (имя) формы')),
                ('phone_field', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона в формате +7 xxxxxxxxxx', regex='^\\+7\\d{10}$')], verbose_name='Номер телефона')),
                ('email_field', models.EmailField(help_text='Поле для почты', max_length=50, verbose_name='Почта')),
                ('text_field', models.TextField(blank=True, max_length=250, null=True, verbose_name='Какой то текст')),
                ('data_field', models.DateField(auto_now_add=True, verbose_name='Дата, видимо дата создания')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
    ]
