# Generated by Django 4.2.7 on 2023-11-20 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_form_phone_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone_field',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона в формате +7xxxxxxxxxx', regex='^\\+7\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
